name: first_quiz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  function_tree: ^0.9.1
  provider: ^6.0.5
  connectivity_plus: ^6.0.3
  battery_plus: ^6.0.1 
  fluttertoast: ^8.2.6
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  file_picker: ^5.3.1
  sqflite: ^2.2.4+1 
  http: ^1.2.2
  get: ^4.6.5
  contacts_service: ^0.6.2
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - image/bgimage.jpg
    - image/grad-skillss.webp
    - image/Flutter-App-development.jpg
    - image/aaai.jpg
    - image/aaaii.jpg
